import Header from '@/_components/layout/Header';
import ThemeToggleButton from '@/_components/ui/ThemeToggleButton';
import { getTheme } from '@/_lib/Theme.server';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dyarmix',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getTheme();
  return (
    <html className={theme === 'dark' ? 'dark' : ''} lang="en">
      <body className={inter.className}>
        <main>
          <Header />
          {children}
          <ThemeToggleButton currentTheme={theme} />
        </main>
      </body>
    </html>
  );
}
